# Generated by Django 5.0.6 on 2024-05-23 19:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_budget_expense_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.budget'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
