# Generated by Django 5.0.6 on 2024-05-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_remove_category_budget_budgetcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='categories',
            field=models.ManyToManyField(through='expenses.BudgetCategory', to='expenses.category'),
        ),
    ]
